<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartCafe.Application\SmartCafe.Application.csproj" />
    <ProjectReference Include="..\SmartCafe.Infrastructure\SmartCafe.Infrastructure.csproj" />
  </ItemGroup>

</Project>